### Site Settings ###
title               : Maxime Raafat
description         : Hi, I'm MAX!
metatag             : I create worlds that do not exist
# Change to empty quotes if you are hosting your site at <your-username>.github.io directly
baseurl             : ''
# Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
repository          : maximeraafat/maximeraafat.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
# Opens external URLs in new tab (works for posts, projects and navbar only)
open_new_tab        : true

github: [metadata]

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Maxime Raafat
  image             : /assets/MaximeRaafat.jpg
  email             : maxime.raafat@yahoo.com
  linkedin          : maximeraafat
  github            : maximeraafat
  gitlab            : maximeraafat
  instagram         : maximeraafat
  youtube           : "@maxnorm"
  # facebook          : your_username
  # behance           : your_username
  # dribbble          : your_username
  # kaggle            : your_username
  # medium            : your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  # twitter           : your_username
  # vimeo             : your_username
  # keybase           : your_username

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:title
  pages:
    output: true
    permalink: /blog/:title
  vision:
    output: true
    permalink: ''

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "vision"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"